### ISSUE TITLE
Extra Rendering of Component

### ISSUE THREAD

**Issue by nimit05** [timsun28/NextJS-Nines-App#162]
const rounds = getAllRounds();
    const [currentRound, setCurrentRound] = useState<number>(0);

    useEffect(() => {
        const gameState = loadGameState();

        if (gameState != null) {
            setCurrentRound(gameState.currentRound);
        }
    }, [setCurrentRound])
    
   This above code is from Components/GameScreen.tsx , Adding SetCurrentRound to dependency array will cause too many rendering , I dont know the exact functionality of this code , if you provide some details on this , i can work on this.

**Comment by timsun28** [comment]
Hi Nimit,

Thank you for creating an issue for this project, 

Because this is a setState function it doesn't change so it will never rerun the code. 
The use effect is used to get the local game state from local storage. 

But feel free to open a pr to remove it as it is not necessarily needed. 

Thank you,
Timo

**Comment by nimit05** [comment]
Ok , thanks for clearing that up.

Thanks
Nimit Wadhwa.

**Comment by nimit05** [comment]
Hi Timo,

You can close this issue.

Thanks
Nimit Wadhwa.
